#
#spring:
#  datasource:
#      url: jdbc:mysql://localhost:3306/users
#      username: root
#      password: 123456789
#
#  jpa:
#    hibernate:
#        ddl-auto: update
#    properties:
#        hibernate:
#          format_sql: true
#          dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher